apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3
spec:
  replicas: 1
  paused: false
  selector:
    matchLabels:
      app: team3
  template:
    metadata:
      labels:
        app: team3
    spec:
      containers:
      - name: team3
        image: Apistone3.azurecr.io/app3:472f3fa9707e539530d75a9a9276cffe1c6fe033
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: team3-service
spec:
  selector:
    app: team3
  type: LoadBalancer
  ports:
  - port: 8181
    targetPort: 80
